In [2]:
import pandas as pd 
from openpyxl import Workbook

In [3]:
df=pd.read_csv("transactions.csv")

In [4]:
df

     Transaction_ID      Customer    Amount  Transaction_Count
0             T0001  Customer_052  90599.72                  2
1             T0002  Customer_093  77375.96                  1
2             T0003  Customer_015  26857.10                  2
3             T0004  Customer_072  64706.34                  1
4             T0005  Customer_061  59777.20                  2
...             ...           ...       ...                ...
2495          T2496  Customer_046  99692.47                  7
2496          T2497  Customer_019  18753.51                  1
2497          T2498  Customer_068  59617.12                  5
2498          T2499  Customer_090  41431.77                  3
2499          T2500  Customer_042  13075.45                  6

[2500 rows x 4 columns]

In [5]:
df["fraud_Status"]="Normal"

In [15]:
df.loc[
    (df["Amount"]>50000)|
    (df["Amount"]<0)|
    (df["Transaction_Count"]>5),
    "Fraud_Status"
]="Suspicion"

In [16]:
df

,Transaction_ID,Customer,Amount,Transaction_Count,fraud_Status,Fraud_Status
0,T0001,Customer_052,90599.72,2,Normal,Suspicion
1,T0002,Customer_093,77375.96,1,Normal,Suspicion
2,T0003,Customer_015,26857.10,2,Normal,NaN
3,T0004,Customer_072,64706.34,1,Normal,Suspicion
4,T0005,Customer_061,59777.20,2,Normal,Suspicion
...,...,...,...,...,...,...
2495,T2496,Customer_046,99692.47,7,Normal,Suspicion
2496,T2497,Customer_019,18753.51,1,Normal,NaN
2497,T2498,Customer_068,59617.12,5,Normal,Suspicion
2498,T2499,Customer_090,41431.77,3,Normal,NaN
2499,T2500,Customer_042,13075.45,6,Normal,Suspicion

In [26]:
wb=Workbook()
ws=wb.active
ws.title="Fraud Report"

In [30]:
for col_num,column_name in enumerate(df.columns, 1):
    ws.cell(row=1,column=col_num,value=column_name)

In [31]:
for raw_num , row in enumerate(df.values,2):
    for col_num,value in enumerate(row,1):
        ws.cell(row=raw_num,column=col_num,value=value)

In [32]:
wb.save("Fraud_Detection_report.xlse")
print("excel report generated successfully")

excel report generated successfully